### ISSUE TITLE
Fails when caching hidden folders

### ISSUE THREAD

**Issue by Minipada** [visualon/jenkins-jobcacher-plugin#39]
Hi,
Thanks for all the patches you did since the upstream.
I noted an issue, It's not critical but the job cacher seems to ignore folders starting with `.`, such as `.git`.

**Comment by repolevedavaj** [comment]
This seems to be because of the default excludes (see `org.apache.tools.ant.DirectoryScanner#DEFAULTEXCLUDES`. To change this, you need to pass the `useDefaultExcludes` parameter while calling the super constructor in `jenkins.plugins.itemstorage.local.LocalObjectPath.IsModifiedGlob#IsModifiedGlob`.

**Comment by viceice** [comment]
can you open a PR to fix that?
